os:
  - linux
python:
  - "2.7"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

dist: trusty
sudo: required
language: python


before_install:
  # Show build setup
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version
  - git --version
  - pip install -r requirements.txt

install:
  # git describe requires complete history
  # - travis_retry git fetch --unshallow
  - python setup.py install
  - pip install -r dev-requirements.txt --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py develop
  - pip install coveralls

script: 
  - python helpTest.py | grep Bat-belt
  - nosetests -v --with-coverage --cover-package=PyGitUpAll


after_success:
  - coveralls
  - echo "OK, all done."

notifications:
  email:
    recipients:
      - ralic.lo.eng@ieee.org
    on_success: always # default: change
    on_failure: never # default: always

